artemis:
    bamboo:
        url: http://localhost:8085
        user: ga38hov    # e.g. ga12abc
        password: FgXYZtfhC6CFNwit
        vcs-application-link-name: Bitbucket
        empty-commit-necessary: true
        authentication-token: secret
