# ===================================================================
# Artemis specific properties
# ===================================================================

artemis:
    repo-clone-path: ./repos/
    repo-download-clone-path: ./repos-download/
    encryption-password: <encrypt-password>     # arbitrary password for encrypting database values
    external-user-management: true              # If false, user management is done using Artemis. True, if you use e.g. Jira, LDAP, etc.
    ldap:
        url: <url>
        user-dn: <user-dn>
        password: <password>
        base: <base>
    jira:
        url: <url>
        user: <user>    # e.g. ga12abc
        password: <password>
        admin-group-name: admins
    version-control:
        url: <url>
        user: <user>                    # e.g. ga12abc
        password: <password>
        secret: <token>                 # VCS API token giving Artemis full Admin access
        ci-token: <token from the CI>   # Token generated by the CI (e.g. Jenkins) for webhooks from the VCS to the CI
    ci:
        url: <url>
        user: <user>                            # e.g. ga12abc
        password: <password>
        vcs-application-link-name: <name>       # If the VCS and CI are directly linked (normally only for Bitbucket + Bamboo)
        empty-commit-necessary: true/false      # Do we need an empty commit for new exercises/repositories in order for the CI to register the repo
        secret-push-token: <token hash>         # Hash of the ci-token, equivalent e.g. to the ci-token in the gitlab.yml
        vcs-credentials: <credentials key>      # Key of the saved credentials for the VCS service
        notification-token: <credentials key>   # Key of the credentials for the Artemis notification token
        secret: <secret>                        # The actual value of the notification token to check against in Artemis
    lti:
        id: artemis_lti
        oauth-key: artemis_lti_key
        oauth-secret: <secret>    # only important for online courses on the edX platform, can typically be ignored
        user-prefix_edx: edx_
        user-prefix_u4i: u4i_
        user-group-name_edx: edx
        user-group-name_u4i: u4i
    git:
        name: Artemis
        email: artemis@in.tum.de
    automatic-text:
        embedding-url: http://localhost:8000/embed
        embedding-chunk-size: 50
        clustering-url: http://localhost:8000/cluster
        segmentation-url: http://localhost:8080/segment
        secret: null
