artemis:
    jenkins:
        url: <Jenkins URL>
        user: artemis
        password: <Artemis Password>
        secret-push-token: <token hash>         # Hash of the ci-token, equivalent e.g. to the ci-token in the gitlab.yml
        git-credentials: <credentials key>      # Key of the saved credentials for the Git service
        notification-token: <credentials key>   # Key of the credentials for the Artemis notification token

# IMPORTANT: you can find all values for the credential keys and the push token in the config.xml of the example Job
