artemis:
    bamboo:
        url: http://localhost:8085
        user: <username>    # e.g. ga12abc
        password: <password>
        vcs-application-link-name: Bitbucket
        empty-commit-necessary: true
        authentication-token: secret
